### ISSUE TITLE
Question: is RSASSA_PSS supported by wrapper code?

### ISSUE THREAD

**Issue by RobertoPrevato** [Synss/python-mbedtls#10]
Hi,
First thing, Thank You for your exceptional work in producing this Cython wrapper for mbedTLS.

I was wondering, is it possible to use RSASSA_PSS to sign bytes with `mbedtls.pk.RSA`? If so, could you please provide an example? I've been looking in the source code, looking how to use `mbedtls_pk_type_t.MBEDTLS_PK_RSASSA_PSS`, but could not find it.

I just noticed that `RSASSA_PSS` is commented in `CIPHER_NAME` tuple, so I suspect this is not implemented?

Kind Regards,
Roberto

**Comment by Synss** [comment]
Hi Roberto,


Thank you for your very nice feedback. I am sorry but as of now, I do not have RSA PSS.

I am currently working (for about one year actually) on adding TLS to the library. It is also mostly working now so that I think I will be able to release it this year. My plan is then to go on with DTLS.

However, I do wrap simpler things sporadically when I get frustrated with the more complex parts of the library. That means that you may get RSA PSS any time within the next 9 months. Adding RSA PSS support would be worth a release. Then, it would be documented in the README as well as in the tests.

That being said, I most certainly accept contributions 😉. Please tell me if you can contribute and I will do my best to help you get started. RSA PSS seems like a good starting point.

**Comment by RobertoPrevato** [comment]
Hi Mathias,
Thank you, in such case I will use `cryptography` library: yesterday night I saw it supports RSA PSS, which I need. I would like to contribute to `python-mbedtls` but I need to think about this, because I am currently working on other projects to contribute to Python community (for example, a library to handle JWT tokens from Azure cloud, maybe OpenID Connect implementation for asyncio), and I don't have much free time. I will drop you an email if I am ready for this. :)

Kind Regards,
Roberto
